# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# aliases
source $HOME/.zsh-aliases

# env
source $HOME/.zsh-env

# zsh theme
ZSH_THEME="spaceship"

# zsh plugins
plugins=(
  git
  osx
  z  
)

source $ZSH/oh-my-zsh.sh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add Yarn and global node_modules binaries to PATH
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
