# Path to your oh-my-zsh installation.
export ZSH="/Users/pra/.oh-my-zsh"

# aliases
source $HOME/.zsh-aliases

# zsh theme
ZSH_THEME="robbyrussell"

# zsh plugins
plugins=(
  git
  osx
  z  
)

source $ZSH/oh-my-zsh.sh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
